### ISSUE TITLE
need some change

### ISSUE THREAD

**Issue by ashim888** [destro014/DSA_Assignment#1]
I've seen you're playing with git that's nice, use git for codes rather than doc files.

folder structure: 

```
- Repository
    - folder
        -file1.c
        -file2.c
        -file3.c
```

if you have codes to be submitted as assignment then use git or else use drive.

And i've seen your commits on other repository of rupesh and posh raj why?
see this:
https://github.com/Shishir999/Assignment_06

**Comment by destro014** [comment]
Okay :D
check it later i will edit it.

On Sun, Jul 17, 2016 at 10:29 PM, Ashim Lamichhane <notifications@github.com

**Comment by destro014** [comment]
they said "mero ma net chaina" so i tried to push their assignment but i don't know what happened.

**Comment by ashim888** [comment]
DONE
